#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MTK_FINGERPRINT_CHIPSAILING_CS358) += chips_driver/
obj-$(CONFIG_MTK_SIMSWAP_AW6302) += aw6302_driver/